const assert = require('node:assert/strict');
const fs = require('node:fs');
const {JSDOM} = require('jsdom');
const apiSource = fs.readFileSync('realtyadda-api.js','utf8');
function environment(page='buy.html') {
  const dom = new JSDOM(fs.readFileSync(page,'utf8'),{url:'https://www.realtyadda.in/'+page,runScripts:'outside-only'});
  const w=dom.window;
  let now=100000;
  w.Date.now=()=>now;
  const requests=[];
  const append=w.document.head.appendChild.bind(w.document.head);
  w.document.head.appendChild = el => { if(el.tagName==='SCRIPT' && el.src.includes('script.google.com')) { requests.push(el); return el; } return append(el); };
  w.eval(apiSource);
  return {dom,w,requests,advance:ms=>now+=ms,reply(data,index=requests.length-1){const u=new URL(requests[index].src);w[u.searchParams.get('callback')](data);}};
}
const tick=()=>new Promise(resolve=>setImmediate(resolve));
(async()=>{
 const e=environment(), a=e.w.RealtyAddaAPI;
 const p={action:'listings',purpose:'Sale',page:1};
 const first=a.read(p), second=a.read(p);
 assert.equal(e.requests.length,1,'concurrent reads share request');
 const items=[{id:'f7746b18-ea42-449d-a7ea-908f71d3a809',title:'3 BHK Independent House',location:'Gayatri garden, Meerut',city:'Meerut',type:'Independent House',bhk:'3 BHK',purpose:'Sale',price:7500000,area:1200,hasPhoto:false}];
 const catalogue={status:'success',listings:items,total:1,pageSize:12};
 e.reply(catalogue); await Promise.all([first,second]);
 (await a.read(p)).listings[0].price=1;
 assert.equal((await a.read(p)).listings[0].price,7500000,'consumers cannot corrupt cached values');
 assert.equal(e.requests.length,1,'repeat navigation uses cache');
 e.w.eval(fs.readFileSync('property-listings.js','utf8')); await tick();
 assert.equal(e.w.document.querySelectorAll('.property').length,1);
 assert.equal(e.requests.length,1,'catalogue renders without another remote call');
 const form=e.w.document.getElementById('listingFilters');
 form.elements.namedItem('city').value='Noida';form.dispatchEvent(new e.w.Event('submit',{cancelable:true}));await tick();
 assert.equal(e.w.document.querySelectorAll('.property').length,0);
 assert.equal(e.requests.length,1,'complete cached catalogue filters locally');
 e.advance(60001);
 assert.equal(a.peek(p),null,'expired public content is not reused');
 const refresh=a.read(p);assert.equal(e.requests.length,2);e.reply(catalogue);await refresh;
 const status1=a.read({action:'status',submissionId:'test'});e.reply({status:'saved'});await status1;
 const status2=a.read({action:'status',submissionId:'test'});assert.equal(e.requests.length,4,'save verification is never cached');e.reply({status:'not_found'});await status2;
 assert.equal(a.peek({action:'status',submissionId:'test'}),null);
 e.dom.window.close();
 const detail=environment('property.html');
 detail.w.history.replaceState(null,'','property.html?id='+items[0].id);
 detail.w.sessionStorage.setItem('ra-property-preview',JSON.stringify({at:100000,item:items[0]}));
 detail.w.eval('const properties = {};\n'+fs.readFileSync('property-gallery.js','utf8'));
 assert.equal(detail.w.document.getElementById('propertyTitle').textContent,items[0].title,'selected listing appears before backend reply');
 assert.match(detail.w.document.getElementById('pageMessage').textContent,/Checking/);
 detail.reply({status:'not_found'});await tick();
 assert.equal(detail.w.document.querySelector('.property-grid').hidden,true,'unpublished property is removed after fresh response');
 detail.dom.window.close();
 const blocked=environment();
 Object.defineProperty(blocked.w,'sessionStorage',{get(){throw new Error('blocked')}});
 const read=blocked.w.RealtyAddaAPI.read(p);blocked.reply(catalogue);await read;
 assert.equal((await blocked.w.RealtyAddaAPI.read(p)).status,'success','storage restrictions do not break reads');
 blocked.dom.window.close();
 console.log('PASS: request deduplication, cache expiry, immutable reads, instant filtering, fresh submission confirmation, immediate preview, publication removal and blocked storage.');
})().catch(error=>{console.error(error);process.exit(1)});
